### PR TITLE
'fromJust' func causes application failure

### PR DESCRIPTION
**Pull request by kapralVV**
- when taglib.c cannot find tag on its side.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Please provide an example of file which causes this. For most part, I believe this shouldn't ever happen, at least it should be safe to assume that every audio file has duration, it can't be `Maybe Duration`. Again, with an example of file that demonstrates the problem, I'll be able to comment better on this.

**Comment by kapralVV** [comment]
Hi,

Let's assume that we download audio files via network and due to some
reason ( it does not matter ) file was not fetched completely.
How it can be modulated ( on Linux )

$ truncate -s 1M some.mp3
You may decrease the value of -s argument to 500K , 300K , ..
$ truncate -s 500K some.mp3
...

As a result you'll see how the duration is decreased after each truncation
and after some iteration you'll get the failure 'fromJust'
Maybe it's not due to Duration but some other value (BitRate, SampleRate)
I'm not sure
So I'm talking about a possible situation when audio file is correct but
due to some reason it's truncated. I've faced with it.
I'll provide the example later if it's necessary.



2016-12-27 16:49 GMT+02:00 Mark Karpov <notifications@github.com>:

**Comment by mrkkrp** [comment]
I would call it corrupted file. The library is designed to work with valid complete files. In fact, if you take a look at how the smart constructors like `mkDuration` are defined, they just reject negative values, and with valid, not corrupted files, you just cannot possibly get negantive duration or sample rate. This is why `fromJust` is used so actively, because `Nothing`  should not ever happen.

I'm not familiar with MP3 format closely enough, but with WAVE or FLAC if you have length of data blog of wrong size, you'll definitely have problems playing it/working with it.

**Comment by mrkkrp** [comment]
Please still provide an example, I'll see what's really going on.

**Comment by mrkkrp** [comment]
This PR contains a breaking API change and I don't see why you expect the library to work in a meaningful way with corrupted files. When you have actual example and minimal example of failing program, please open an issue for discussion/investigation. Closing this for now.

**Pull request closed without merging**
